name: Bump UV lockfile

on:
  workflow_dispatch:  # Allows manual trigger

  schedule:
    - cron:  '0 0 * * 1'  # 12AM only on Mondays

jobs:
  bump-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Update lockfile
        run: |
          # Remove lockfile to force update
          rm production.uv.lock
          pre-commit run update-uv-env --all-files || true

      - name: Generate new requirements.txt
        run : |
          pre-commit run update-requirements --all-files || true

      - name: Detect if changes were made
        id: git-diff
        run: |
          changes=false
          git diff --exit-code || changes=true
          echo "update_done=$changes" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-diff.outputs.update_done == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
            token: ${{ secrets.PL_PASTEURBOT_PAT_PUBLIC }}
            committer: PasteurBot <${{ vars.PL_PASTEURBOT_EMAIL }}>
            author: PasteurBot <${{ vars.PL_PASTEURBOT_EMAIL }}>
            commit-message: "chore: update dependencies"
            title: "chore: ðŸ“¦ update dependencies"
            branch: _bot/update-deps
            draft: false
            base: main
            body: |
              This PR updates the lockfile to the latest versions of the dependencies.
              Please review the changes and merge when ready.
